version: "3"
services:
  django-web:
    container_name: django-web
    image: logicpuzzle-test:1.0.0 # 이미지, 태그
    ports:
        - "8080:8080"
    build: ./
    volumes:
        - ./srv/logicpuzzle_web:/path/in/container
        - ./log/uwsgi:/log
  nginx:
    container_name: nginx
    image: nginx
    ports:
        - "80:80"
    build: ./nginx
    volumes:
        - ./srv/logicpuzzle_web:/path/in/container
        - ./log/nginx:/log
        - ./.static_root:/static
    depends_on :
        - django-web