version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./.static_root:/.static_root
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: >
        bash -c "python manage.py collectstatic --noinput
        && python3 manage.py migrate
        && gunicorn logicPuzzle.wsgi:application --bind 0.0.0.0:8080 --log-level=debug --access-logfile=- --log-file=-"
    volumes:
      - ./.static_root:/usr/arc/app/staticfiles
    expose:
      - "8080"
    depends_on:
      - redis
  redis:
    container_name: redis_service
    image: redis
    ports:
      - "6379:6379"
    restart: always
