<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-07-26 18:43
=======
# Generated by Django 5.0.7 on 2024-08-22 05:58
>>>>>>> b1a42273d14747a7e473f1904d1d7b508364f847

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
<<<<<<< HEAD
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, choices=[('refrigerated', '냉장'), ('frozen', '냉동'), ('outdoor', '실외')], max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
=======
                ('ocr', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, choices=[('냉장', '냉장'), ('냉동', '냉동'), ('실외', '실외')], max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
>>>>>>> b1a42273d14747a7e473f1904d1d7b508364f847
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
