# Generated by Django 5.0.7 on 2024-09-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
