# Generated by Django 5.1.1 on 2024-10-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_product_table'),
        ('production', '0005_alter_product_expiration_date'),
    ]

    operations = [
    ]
