# Generated by Django 5.0.7 on 2024-11-06 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_merge_20241005_2019'),
        ('user', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
    ]
