# Generated by Django 5.0.7 on 2024-11-06 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_profile_user'),
        ('user', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
    ]
