# Generated by Django 5.0.7 on 2024-11-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_waste', '0002_alter_foodwaste_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwaste',
            name='quantity',
            field=models.FloatField(choices=[(1, '1L'), (3, '3L'), (5, '5L'), (10, '10L'), (20, '20L')]),
        ),
    ]
