# Generated by Django 5.0.7 on 2024-09-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table='notice',
        ),
    ]
