<<<<<<< HEAD

# Generated by Django 5.0.7 on 2024-09-16 02:22

# Generated by Django 5.0.7 on 2024-09-19 23:48


=======
# Generated by Django 5.0.7 on 2024-09-16 02:22

>>>>>>> 50ec3df6b7ce62d40ca67e13bb67da7fb073fd1e
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
